source 'https://rubygems.org'
gem 'rails', '~> 6.0', '>= 6.0.3.5'
gem 'mysql2'
gem 'sass-rails', '>= 5.0.8'
gem 'uglifier'
gem 'coffee-rails', '>= 4.2.2'
gem 'jquery-rails', '>= 4.3.1'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks', '>= 1.3.0'
gem 'authie'
gem 'kaminari', '>= 1.1.1'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt'
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey'
gem 'nifty-attachments'
gem 'puma'
gem 'moonrope'
gem 'florrick'
gem 'delayed_job_active_record', '>= 4.1.3'
gem 'foreman'
gem 'redcarpet'
gem 'premailer'
gem 'rack-custom-proxies'
gem 'log_logins', '>= 1.0.2'

group :development, :test do
  gem 'annotate', '~> 2.6.7'
end
