source 'https://rubygems.org'
gem 'rails', '~> 5.2', '>= 5.2.4.4'
gem 'mysql2'
gem 'sass-rails', '>= 5.0.7'
gem 'uglifier'
gem 'coffee-rails', '>= 4.2.2'
gem 'jquery-rails', '>= 4.3.1'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'authie'
gem 'kaminari', '>= 1.1.1'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt'
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey'
gem 'nifty-attachments'
gem 'puma'
gem 'moonrope'
gem 'florrick'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet'
gem 'premailer'
gem 'rack-custom-proxies'
gem 'log_logins'

group :development, :test do
  gem 'annotate', '~> 2.6.5'
end
